name: NodeJS with pkg and tsc
on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+
  pull_request:
    tags: v[1-9]+.[0-9]+.[0-9]+
      jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm run build
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          prerelease: false
          files: |
            assets/*
            build/binaries/*


name: NodeJS with pkg and tsc prerelease
on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+-pre
  pull_request:
    tags: v[1-9]+.[0-9]+.[0-9]+-pre
      jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm run build
        
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          prerelease: true
          title: "Development Build"
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          files: |
            assets/*
            build/binaries/*
